id: 1ae291ff67d540f1b4129b5b460585c2
initial_creation_type: ocr
source_metadata:
  volumes:
    7998866ad54741e2a449f91038b9d5dd:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ''
      total_pages: 1902
      volume_number: 26
